
apiVersion: v1
kind: Service
metadata:
  name: map-app-fe-service
spec:
  selector:
    app: map-app-fe
  ports:
  - name: map-app-fe-proxy
    port: 3000
    targetPort: 3000
  type: LoadBalancer

     